"""Shell completion generator — builds PowerShell, Bash, and Zsh completion
scripts from argparse parser introspection.

HB-01: All completions derived from argparse metadata. No hardcoded command lists.
"""
from __future__ import annotations

import argparse
from collections.abc import Sequence


class CompletionGenerator:
    """Generate shell completion scripts from an argparse parser."""

    def __init__(self, parser: argparse.ArgumentParser) -> None:
        self._parser = parser

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, shell: str) -> str:
        """Return completion script for *shell* (powershell|bash|zsh)."""
        dispatch = {
            "powershell": self.generate_powershell,
            "bash": self.generate_bash,
            "zsh": self.generate_zsh,
        }
        key = shell.lower().strip()
        if key not in dispatch:
            raise ValueError(
                f"Unsupported shell '{shell}'. Choose from: {', '.join(dispatch)}"
            )
        return dispatch[key]()

    def generate_powershell(self) -> str:
        """Generate a PowerShell Register-ArgumentCompleter script."""
        prog = self._parser.prog or "deskaoy"
        commands = self._collect_commands()
        lines: list[str] = [
            f"# PowerShell completion for {prog}",
            f"# Generated by `{prog} completions powershell`",
            "using namespace System.Management.Automation",
            "using namespace System.Management.Automation.Language",
            "",
            f"Register-ArgumentCompleter -CommandName '{prog}' -ScriptBlock {{",
            "    param($wordToComplete, $commandAst, $cursorPosition)",
            "",
            "    # Collect tokens from the command line",
            "    $tokens = $commandAst.CommandElements | ForEach-Object { $_.Value }",
            "    $tokens = @($tokens)",
            "",
            "    # Top-level completions",
            "    $topCommands = @(",
        ]
        for cmd_name in commands:
            lines.append(f"        '{cmd_name}'")
        lines.append("    )")

        lines += [
            "",
            "    $topOptions = @(",
        ]
        for opt in self._collect_global_options():
            lines.append(f"        '{opt}'")
        lines.append("    )")

        # Per-subcommand option completions
        lines += [
            "",
            "    # Determine context",
            "    if ($tokens.Count -le 1) {",
            "        # Completing after program name",
            "        $all = $topCommands + $topOptions",
            "        $all | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {",
            "            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)",
            "        }",
            "        return",
            "    }",
            "",
            "    $subCmd = $tokens[1]",
            "",
            "    # If completing the subcommand itself",
            "    if ($subCmd -like \"$wordToComplete*\" -and -not ($topCommands -contains $subCmd)) {",
            "        $topCommands | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {",
            "            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)",
            "        }",
            "        return",
            "    }",
        ]

        # Per-command option block
        for cmd_name, cmd_opts in self._collect_command_options().items():
            cmd_name.replace("-", "_")
            lines += [
                "",
                f"    if ($subCmd -eq '{cmd_name}') {{",
                "        $options = @(",
            ]
            for opt in cmd_opts:
                lines.append(f"            '{opt}'")
            lines += [
                "        )",
                "        $options + $topOptions | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {",
                "            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)",
                "        }",
                "        return",
                "    }",
            ]

        # Fallback: global options
        lines += [
            "",
            "    # Fallback: global options",
            "    $topOptions | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {",
            "        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)",
            "    }",
            "}",
        ]
        return "\n".join(lines)

    def generate_bash(self) -> str:
        """Generate a Bash complete -F function."""
        prog = self._parser.prog or "deskaoy"
        fn_name = f"_{prog.replace('-', '_')}_completion"
        commands = self._collect_commands()
        global_opts = self._collect_global_options()
        cmd_options = self._collect_command_options()

        lines: list[str] = [
            f"# Bash completion for {prog}",
            f"# Generated by `{prog} completions bash`",
            f"# Install: source <({prog} completions bash) or add to ~/.bashrc",
            "",
            f"{fn_name}() {{",
            "    local cur prev words cword",
            "    _init_completion || return",
            "",
            f"    local commands='{self._join(commands)}'",
            f"    local global_opts='{self._join(global_opts)}'",
        ]

        # Per-command options
        for cmd_name, cmd_opts in cmd_options.items():
            safe_var = cmd_name.replace("-", "_")
            lines.append(
                f"    local {safe_var}_opts='{self._join(cmd_opts)}'"
            )

        lines += [
            "",
            "    # Command is first positional after program",
            "    if [ $cword -eq 1 ]; then",
            "        COMPREPLY=($(compgen -W \"$commands $global_opts\" -- \"$cur\"))",
            "        return",
            "    fi",
            "",
            "    local subcmd=${words[1]}",
            "",
            "    # If completing subcommand name",
            "    if [ $cword -eq 1 ] || [[ ! \" $commands \" =~ \" $subcmd \" ]]; then",
            "        COMPREPLY=($(compgen -W \"$commands $global_opts\" -- \"$cur\"))",
            "        return",
            "    fi",
        ]

        # Per-command option completion
        for cmd_name, cmd_opts in cmd_options.items():
            safe_var = cmd_name.replace("-", "_")
            lines += [
                "",
                f"    if [ \"$subcmd\" = \"{cmd_name}\" ]; then",
                f"        COMPREPLY=($(compgen -W \"${safe_var}_opts $global_opts\" -- \"$cur\"))",
                "        return",
                "    fi",
            ]

        lines += [
            "",
            "    # Fallback",
            "    COMPREPLY=($(compgen -W \"$global_opts\" -- \"$cur\"))",
            "}",
            "",
            f"complete -F {fn_name} {prog}",
        ]
        return "\n".join(lines)

    def generate_zsh(self) -> str:
        """Generate a Zsh compdef function."""
        prog = self._parser.prog or "deskaoy"
        self._collect_commands()
        global_opts = self._collect_global_options()
        cmd_options = self._collect_command_options()

        lines: list[str] = [
            f"#compdef {prog}",
            f"# Zsh completion for {prog}",
            f"# Generated by `{prog} completions zsh`",
            f"# Install: fpath=(~/.zsh/completion $fpath) or source <({prog} completions zsh)",
            "",
            f"function _{prog.replace('-', '_')} {{",
            "    local -a commands",
            "    commands=(",
        ]
        for cmd_name, help_text in self._collect_commands_with_help().items():
            lines.append(f"        '{cmd_name}:{help_text}'")
        lines.append("    )")

        lines += [
            "",
            "    _arguments -C \\",
        ]
        # Global options as _arguments specs
        for opt_str in global_opts:
            lines.append(f"        '{opt_str}' \\")
        lines.append('        "1:command:->command" \\')
        lines.append('        "*::arg:->args"')

        lines += [
            "",
            "    case $state in",
            "        command)",
            "            _describe 'command' commands",
            "            ;;",
            "        args)",
            "            case $words[1] in",
        ]

        for cmd_name, cmd_opts in cmd_options.items():
            if not cmd_opts:
                continue
            lines.append(f"                {cmd_name})")
            lines.append("                    _arguments \\")
            for i, opt_str in enumerate(cmd_opts):
                suffix = " \\" if i < len(cmd_opts) - 1 else ""
                lines.append(f"                        '{opt_str}'{suffix}")
            lines.append("                    ;;")

        lines += [
            "            esac",
            "            ;;",
            "    esac",
            "}",
            "",
            f"_{prog.replace('-', '_')} \"$@\"",
        ]
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Introspection helpers
    # ------------------------------------------------------------------

    def _collect_commands(self) -> list[str]:
        """Collect top-level subcommand names from the parser."""
        names: list[str] = []
        for action in self._parser._actions:
            if isinstance(action, argparse._SubParsersAction):
                for name in sorted(action.choices.keys()):
                    names.append(name)
        return names

    def _collect_commands_with_help(self) -> dict[str, str]:
        """Collect subcommand names with their help text."""
        result: dict[str, str] = {}
        for action in self._parser._actions:
            if isinstance(action, argparse._SubParsersAction):
                # Build lookup from the action's choices dict for help text
                help_map: dict[str, str] = {}
                for choice_name, choice_help in action.choices.items():
                    # description is the help text set via add_parser(help=...)
                    text = choice_help.description or ""
                    help_map[choice_name] = text
                # Also try the _name_parser_map-style helptext from action
                for name, sub_parser in action.choices.items():
                    text = help_map.get(name, "")
                    if not text:
                        # Try to get help from the action's metavar descriptions
                        text = getattr(sub_parser, "description", "") or ""
                    text = text.replace(":", "\\:").replace("'", "'\\''")
                    result[name] = text
        return result

    def _collect_global_options(self) -> list[str]:
        """Collect global option strings (excluding help)."""
        opts: list[str] = []
        for action in self._parser._actions:
            if isinstance(action, argparse._SubParsersAction):
                continue
            if action.option_strings and action.dest != "help":
                for opt in action.option_strings:
                    opts.append(opt)
        return opts

    def _collect_command_options(self) -> dict[str, list[str]]:
        """Collect per-subcommand option strings."""
        result: dict[str, list[str]] = {}
        for action in self._parser._actions:
            if isinstance(action, argparse._SubParsersAction):
                for name, sub_parser in action.choices.items():
                    cmd_opts: list[str] = []
                    for sub_action in sub_parser._actions:
                        if isinstance(sub_action, argparse._SubParsersAction):
                            # Nested subcommands — collect them as positional completions
                            for sub_name in sorted(sub_action.choices.keys()):
                                cmd_opts.append(sub_name)
                        elif sub_action.option_strings and sub_action.dest != "help":
                            for opt in sub_action.option_strings:
                                cmd_opts.append(opt)
                    if cmd_opts:
                        result[name] = cmd_opts
        return result

    @staticmethod
    def _join(items: Sequence[str]) -> str:
        """Join items into a space-separated string for shell scripts."""
        return " ".join(items)
